#!/usr/bin/env bash
# dev-console.sh — run the in-cluster console LOCALLY against a live instance's
# cluster, using SSH local port-forwards (ssh -L). Unlike sshuttle this needs NO
# laptop sudo for the tunnels (ssh -L is unprivileged) — only the optional Kafka
# /etc/hosts alias touches sudo (one line). The K8s tunnel is the same one that
# lists pods reliably; we forward each service the console needs.
#
# Usage:
#   scripts/dev-console.sh --instance <name> [--port N] [--no-dev] [--with-hosts]
#
#   --instance <name>   instance under scripts/instances/<name>/ (required)
#   --port <N>          dev-server port (default 5003). Use another (e.g. 5013)
#                       to run ALONGSIDE the menubar-managed console on :5003.
#   --no-dev            set up tunnels + .env.local but don't start a server.
#   --with-hosts        add the Kafka advertised-name alias to /etc/hosts
#                       (127.0.0.1 kafka-kafka — sudo; removed on exit). Without
#                       it Kafka stays "unreachable" (see the printed note).
#
# Forwarded:  127.0.0.1:16443 → apiserver(:6443)   ·   127.0.0.1:9092 → kafka
# S3 goes over the public ARTESCA vhost (no tunnel).
# Known gaps: Prometheus (ARTESCA auth → 401, console sends no creds) and
# camera-sim (a separate instance) stay unreachable.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"
# shellcheck source=lib-remote.sh
source "$HERE/lib-remote.sh"

INSTANCE=""; START_DEV=1; WITH_HOSTS=0; DEV_PORT=5003
while [[ $# -gt 0 ]]; do
  case "$1" in
    --instance) INSTANCE="$2"; shift 2 ;;
    --instance=*) INSTANCE="${1#--instance=}"; shift ;;
    --no-dev) START_DEV=0; shift ;;
    --with-hosts) WITH_HOSTS=1; shift ;;
    --port) DEV_PORT="$2"; shift 2 ;;
    --port=*) DEV_PORT="${1#--port=}"; shift ;;
    -h|--help) sed -n '2,30p' "$0"; exit 0 ;;
    *) echo "unknown arg: $1" >&2; exit 2 ;;
  esac
done
[[ -n "$INSTANCE" ]] || { echo "error: --instance <name> required" >&2; exit 2; }
INST_DIR="$REPO_ROOT/scripts/instances/$INSTANCE"
[[ -d "$INST_DIR" ]] || { echo "error: $INST_DIR not found" >&2; exit 2; }

say() { printf '\033[1;36m[dev-console]\033[0m %s\n' "$*"; }

# Local forward ports.
K8S_PORT=16443
KAFKA_PORT=9092
for p in "$DEV_PORT" "$K8S_PORT" "$KAFKA_PORT"; do
  if lsof -nP -iTCP:"$p" -sTCP:LISTEN >/dev/null 2>&1; then
    [[ "$p" == "$DEV_PORT" && "$START_DEV" -eq 0 ]] && continue
    echo "error: port $p already in use." >&2
    [[ "$p" == "$DEV_PORT" ]] && echo "       :5003 is normally the menubar console — run with --port 5013 to run alongside." >&2
    echo "       free it:  lsof -ti :$p | xargs kill" >&2
    exit 2
  fi
done

# ── Load instance state ──────────────────────────────────────────────────────
set -a
# shellcheck disable=SC1091
source "$INST_DIR/.stack-state.env"
[[ -f "$INST_DIR/.objectstore.env" ]] && source "$INST_DIR/.objectstore.env"
set +a
remote_init
PRIV_IP="${PRIV_IP:-10.42.1.10}"

# ── 1. Fetch + rewrite kubeconfig for the local tunnel ────────────────────────
KCFG="$INST_DIR/.dev-console.kubeconfig"
say "Fetching kubeconfig from node → $KCFG"
rsh "sudo -n kubectl --kubeconfig=/etc/kubernetes/admin.conf config view --raw -o yaml 2>/dev/null" \
  | grep -avE 'WARNING|authorized|monitor|consent|criminal|law enforce|officials|personnel|------' > "$KCFG"
grep -q "server: https://" "$KCFG" || { echo "error: kubeconfig fetch failed" >&2; exit 1; }
# Point at the local tunnel; the apiserver cert is for $PRIV_IP, not 127.0.0.1,
# so swap the CA for insecure-skip-tls-verify (lab-only).
sed -i '' -E \
  -e "s#server: https://[0-9.]+:6443#server: https://127.0.0.1:${K8S_PORT}#" \
  -e 's#certificate-authority-data:.*#insecure-skip-tls-verify: true#' \
  "$KCFG"
chmod 600 "$KCFG"

# ── 2. Discover Kafka ClusterIP + VSS namespace ───────────────────────────────
K="sudo -n kubectl --kubeconfig=/etc/kubernetes/admin.conf"
VSS_NS="${STACK_ID:+vss-${SCALITY_BP_PROFILE:-alerts}}"; VSS_NS="${VSS_NS:-vss-alerts}"
KAFKA_IP="$(rsh "$K -n $VSS_NS get svc kafka-kafka -o jsonpath='{.spec.clusterIP}' 2>/dev/null" 2>/dev/null | grep -oE '^[0-9.]+' | head -1)"
say "ns=$VSS_NS  kafka=${KAFKA_IP:-?}  (K8s→127.0.0.1:$K8S_PORT, Kafka→127.0.0.1:$KAFKA_PORT)"

# ── 3. Write console/.env.local ───────────────────────────────────────────────
ENVF="$REPO_ROOT/console/.env.local"
say "Writing $ENVF"
{
  echo "# Generated by scripts/dev-console.sh for '$INSTANCE' — do not commit."
  echo "CONSOLE_DISABLE_AUTH=true"
  echo "KUBECONFIG=$KCFG"
  echo "VSS_NAMESPACE=$VSS_NS"
  if [[ -n "${OBJECTSTORE_ENDPOINT:-}" ]]; then
    echo "OBJECTSTORE_ENDPOINT=https://s3.artesca.isv-lab.local"
    echo "OBJECTSTORE_ENDPOINT_IP=${PUB_IP}"
    echo "OBJECTSTORE_TLS_INSECURE=true"
    echo "OBJECTSTORE_REGION=${OBJECTSTORE_REGION:-us-east-1}"
    echo "OBJECTSTORE_BUCKET=${OBJECTSTORE_BUCKET:-nvidia-vss-recordings}"
    [[ -n "${OBJECTSTORE_ACCESS_KEY_ID:-}" ]] && echo "OBJECTSTORE_ACCESS_KEY_ID=${OBJECTSTORE_ACCESS_KEY_ID}"
    [[ -n "${OBJECTSTORE_SECRET_ACCESS_KEY:-}" ]] && echo "OBJECTSTORE_SECRET_ACCESS_KEY=${OBJECTSTORE_SECRET_ACCESS_KEY}"
  fi
  # Kafka advertises `kafka-kafka:9092`; with the hosts alias that resolves to
  # 127.0.0.1 → the local forward. Bootstrap uses the same name for consistency.
  [[ -n "${KAFKA_IP:-}" ]] && echo "KAFKA_BROKERS=kafka-kafka:${KAFKA_PORT}"
} > "$ENVF"

# ── 4. /etc/hosts alias for Kafka. Redpanda advertises itself as `kafka-kafka:9092`,
#       so the client must resolve that name to the local forward (bootstrapping on
#       127.0.0.1 alone isn't enough — the broker redirects to its advertised name).
#       The alias is PERSISTENT + idempotent: laid down once (needs sudo), then reused
#       by no-sudo runs — notably the menubar-managed console, which can't sudo per
#       launch. NOT removed on exit, so a single `--with-hosts` run enables Kafka for
#       good (a 127.0.0.1 alias is harmless when no tunnel is up — just conn-refused).
HOSTS_OK=0
if grep -qE '^[0-9.]+[[:space:]]+kafka-kafka([[:space:]]|#|$)' /etc/hosts 2>/dev/null; then
  HOSTS_OK=1
elif [[ "$WITH_HOSTS" -eq 1 && -n "${KAFKA_IP:-}" ]]; then
  say "Adding persistent /etc/hosts alias: 127.0.0.1 kafka-kafka (sudo, one-time)"
  echo "127.0.0.1 kafka-kafka  # dev-console (persistent — Kafka advertised name)" \
    | sudo tee -a /etc/hosts >/dev/null && HOSTS_OK=1
fi

# ── 5. Open the SSH local forwards (no sudo) ──────────────────────────────────
# ControlMaster off so the forward doesn't graft onto a shared multiplex master
# (the footgun that broke -L tunnels before — see lib-kubectl.sh).
FWD=( -L "${K8S_PORT}:${PRIV_IP}:6443" )
[[ -n "${KAFKA_IP:-}" ]] && FWD+=( -L "${KAFKA_PORT}:${KAFKA_IP}:9092" )
say "Opening SSH forwards → $REMOTE_SSH_TARGET"
# LogLevel=QUIET suppresses the node's pre-auth login Banner (the long
# "authorized users only" block) that otherwise floods the menubar logs.
ssh -o ControlMaster=no -o ControlPath=none -o ExitOnForwardFailure=yes -o LogLevel=QUIET \
  "${REMOTE_SSH_OPTS[@]}" "${FWD[@]}" -N "$REMOTE_SSH_TARGET" &
SSH_PID=$!
trap 'kill "$SSH_PID" 2>/dev/null || true' EXIT

say "Waiting for the K8s forward (127.0.0.1:$K8S_PORT)…"
OK=0
for _i in $(seq 1 15); do
  if nc -z 127.0.0.1 "$K8S_PORT" 2>/dev/null; then OK=1; break; fi
  kill -0 "$SSH_PID" 2>/dev/null || { echo "error: ssh forward exited (check the key / node)" >&2; exit 1; }
  sleep 1
done
[[ "$OK" -eq 1 ]] || { echo "error: K8s forward never came up on 127.0.0.1:$K8S_PORT" >&2; exit 1; }
say "  ✓ K8s API reachable via the tunnel"

# ── 6. Notes + start the dev server ───────────────────────────────────────────
cat <<NOTE

  ✓ K8s API + S3 wired. Kafka: $([[ "$HOSTS_OK" -eq 1 ]] && echo "kafka-kafka alias present → reachable" || echo "unreachable — run once with --with-hosts to add the persistent 127.0.0.1 kafka-kafka alias (sudo)")
  ⚠ Prometheus stays unreachable (ARTESCA auth; console sends no creds).
  ⚠ camera-sim is a separate instance, not in this cluster.

NOTE

# If the console is ALREADY serving on its own port, reuse it rather than starting
# a second `next dev` (which would fail on the per-directory .next/dev lock).
# Detect by the console's OWN port — NOT `pgrep next dev`, which also matches the
# deployer's `next dev --port 5002` in a different directory and caused a false
# "already running" that skipped the server start and left :$DEV_PORT down.
if [[ "$START_DEV" -eq 1 ]] && nc -z 127.0.0.1 "$DEV_PORT" 2>/dev/null; then
  say "A console dev server is already serving on :$DEV_PORT — reusing it (not starting a second)."
  START_DEV=0
fi

if [[ "$START_DEV" -eq 1 ]]; then
  say "Starting console dev server on http://localhost:$DEV_PORT (Ctrl-C stops it + tears down tunnels)"
  cd "$REPO_ROOT/console"
  npx next dev --port "$DEV_PORT"
else
  echo ""
  say "Tunnels + .env.local + hosts are in place and HELD by this process."
  say "→ Restart the menubar-managed console so it reloads .env.local:"
  say "    Scality menubar → (console server) → Restart"
  say "→ Then open  http://localhost:5003  — K8s / Kafka / S3 should be green."
  say "Keep this process alive (the tunnels live here). Ctrl-C / stopping it tears them down."
  # wait (not `read`) so it also holds when launched without a TTY (e.g. the menubar).
  wait "$SSH_PID"
fi
